name: automation test
run-name: ${{github.actor}} run this project
on: [push]
jobs:
  run-test-case:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Cache virtualenv
        uses: actions/cache@v3
        with:
          key: venv-${{ runner.os }}-${{ steps.setup_python.outputs.python-version}}-${{ hashFiles('requirements.txt') }}
          path: .venv

      - name: install dependencies
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          python3 -m pip install -r requirements.txt
          robot --outputdir report testcases/

      - name: generate test report
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: report
          path: report/

          

