name: automation test
run-name: ${{github.actor}} run this project
on: [push]
jobs:
  run-test-case:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
